### ISSUE TITLE
Minimum Screen Size Message

### ISSUE THREAD

**Issue by Orkan23** [BeniEnge/as_son_of_hunkypunk#11]
Checking whether the error message comes up reasonable:
"Sorry, but your screen is too small to play Theatre.  Minimum screen size is 20
by 50 characters."

Check if it is fixable
Temporary workaround: 
When open first time: set display to landscape mode and then open "Theatre"

**Comment by dgarkov** [comment]
Fixed for any mode with an Alert Dialog, shown only on first `Open`. For exact implementation: [here](https://github.com/BeniEnge/as_son_of_hunkypunk/commit/0d67af5ca905e039d1fcca9b449d9e02026aaf55). Possible TODO - Extend for any other such game by fetching a minimum size screen and not only for the given case.
